import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import HeroSection from "@/components/HeroSectionComponent";
import Nav from "@/components/NavComponent";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Alex Souchereau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Nav></Nav>
          <HeroSection></HeroSection>
      </main>
      <Footer></Footer>
    </>
  )
}
